[project]
name = "lnkd-report"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playwright>=1.52.0",
    "polars>=1.30.0",
    "pydantic>=2.11.7",
    "pytest-playwright>=0.7.0",
    "ruamel-yaml>=0.18.14",
]
