---
title: "LinkedIn Post Report - "
format: html
---

## Posts by Author


### Denise M Roche
- **Date**: 2025-06-15 22:28:49.454899
- **URL**: [View Post](https://www.linkedin.com/feed/update/urn:li:activity:7339409375498842113)
- **Hashtags**: None

**Content:**
Today we had an opportunity to appreciate the service of our Head of Department Professor Eric Raymond Igou. This is a selfless position in academia. It was clear to see how appreciated Eric is by the thoughtful gifts 🎁 our staff and faculty presented. Thank you Eric from your colleagues in Department of Psychology, University of Limerick

---

### Denise M Roche
- **Date**: 2025-06-15 22:28:50.311439
- **URL**: [View Post](https://www.linkedin.com/feed/update/urn:li:activity:7337913108788625408)
- **Hashtags**: hashtag#Sharepoint

**Content:**
Opportunities for knowledge-sharing are very valuable in our everyday work lives. Was delighted to share and see how my colleagues across UL Campus use hashtag#Sharepoint to make their work more efficient, accessible  and inclusive 🙌

---

### Denise M Roche
- **Date**: 2025-06-15 22:28:51.580057
- **URL**: [View Post](https://www.linkedin.com/feed/update/urn:li:activity:7335784105881604101)
- **Hashtags**: None

**Content:**
Great article, insightful 👏

---

### Elaine L. Kinsella, PhD
- **Date**: 2025-06-15 22:29:12.005765
- **URL**: [View Post](https://www.linkedin.com/feed/update/urn:li:activity:7339898779694718978)
- **Hashtags**: None

**Content:**
The Irish Times view on Ireland’s research agenda: the vital role of innovationhttps://lnkd.in/eV4Rtd8c

---

### Elaine L. Kinsella, PhD
- **Date**: 2025-06-15 22:29:12.064882
- **URL**: [View Post](https://www.linkedin.com/feed/update/urn:li:activity:7339897503783247872)
- **Hashtags**: None

**Content:**
https://lnkd.in/ez6gPjiZ

---
